### ISSUE TITLE
Inconsistency with regex handling.

### ISSUE THREAD

**Issue by social-anthrax** [yellowtides/owenbot-hs#13]
All commands should be handled within Command Handler, with some exceptions for the random rolling functions. 
However isFortune, isADA, isThatcher and isNietzsche are all residing within handleEvent.hs making it extremely cluttered.

These should be migrated to CommandHandler.

**Comment by yellowtides** [comment]
True, haven't considered that we'd get to the point of having so many miscellaneous functions. I think that we should have a seperate miscellaneous folder with all the misc. functionality/REs. Files like `ADAPriceFetcher.hs` should also be moved there.

**Comment by social-anthrax** [comment]
As it stands it should be easy for them to be moved straight into the command handler file without any loss of functionality. The files that should be allowed to be there are the ones to do with rolling and random chance.
