### ISSUE TITLE
Stop using discord role names and use ID's for critical systems.

### ISSUE THREAD

**Issue by social-anthrax** [yellowtides/owenbot-hs#14]
As discussed in the dev channel.

**Comment by social-anthrax** [comment]
Mostly fixed, need to check how it fits in with refactor

**Comment by yutotakano** [comment]
Should all be good actually, since it only uses `devs.csv` now.

**Comment by social-anthrax** [comment]
@yutotakano permission to close issue?

**Comment by social-anthrax** [comment]
Closing as per @yutotakano's permission
