### ISSUE TITLE
Add some useful help messages for each command

### ISSUE THREAD

**Issue by yutotakano** [yellowtides/owenbot-hs#36]
Title. 

Compose the `help` function onto existing commands to add helpful messages to display when `:helpme (name)` is used.

**Comment by himanshu007-creator** [comment]
hi, i would like to work on this issue. I just installed haskel in my machine, and did some tutorials.
I would like to get more of it, so if you could guide me a bit, i think i can help😊

**Comment by social-anthrax** [comment]
Thank you for your offer to help @himanshu007-creator! Sadly at the moment our team consists of students at the moment, so we can't afford the time to explain basic Haskell concepts. The current help function relies heavily on monadic functions, which are relatively advanced, and aren't suitable for complete beginners new to the language.  If you'd like we'd be happy to point you towards good beginners resources.  We wish you luck on your Haskell journey!

**Comment by himanshu007-creator** [comment]
> Thank you for your offer to help @himanshu007-creator! Sadly at the moment our team consists of students at the moment, so we can't afford the time to explain basic Haskell concepts. The current help function relies heavily on monadic functions, which are relatively advanced, and aren't suitable for complete beginners new to the language. If you'd like we'd be happy to point you towards good beginners resources. We wish you luck on your Haskell journey!

Sure, ill like to solve good beginner issues then

**Comment by social-anthrax** [comment]
I don't think we have any tasks in the codebase suitable to your background right now @himanshu007-creator. If you are wanting to develop your Haskell knowledge then I would recommend you start with ["Learn You a Haskell for a Great Good"](http://learnyouahaskell.com/)

**Comment by yutotakano** [comment]
As far as I've checked around in the code, this is complete and can be closed.
